name: Test Action

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: krishnasaikeerthan.nagandla@gramener.com
        run: echo "Hello, world!"
